#!/usr/bin/env bash
#
# Turns the `helm show all` captures in charts/*.txt into js/charts.js.
#
# Each capture holds three YAML documents: Chart.yaml, values.yaml and the
# chart README. This script extracts, per chart:
#   chart   - version/appVersion/description from Chart.yaml
#   values  - the full default values tree
#   options - the documented options from the README's Common/Advanced tables
#
# The output is pure extraction: interpreting an option's type or allowed
# values is left to js/app.js.
#
# Usage: scripts/gen-chart-data.sh
# Requires: yq, jq, awk

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
charts_dir="${repo_root}/charts"
out_file="${repo_root}/js/charts.js"

for tool in yq jq awk; do
  command -v "$tool" >/dev/null || { echo "missing required tool: $tool" >&2; exit 1; }
done

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Splits a capture into $work/doc1 (Chart.yaml), doc2 (values.yaml), doc3 (README).
split_docs() {
  awk -v out="$work" '
    /^---$/ && doc < 3 { doc++; next }
    { print > (out "/doc" (doc + 1)) }
  ' doc=0 "$1"
}

# Reads the README markdown tables under "#### Common Options" and
# "#### Advanced Options" into [{path, default, description, section}].
parse_options() {
  awk '
    function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }
    function unwrap(s) { gsub(/`/, "", s); return trim(s) }
    function esc(s) {
      gsub(/\\/, "\\\\", s); gsub(/"/, "\\\"", s); gsub(/\t/, " ", s); return s
    }

    /^#### Common Options/   { section = "common"; next }
    /^#### Advanced Options/ { section = "advanced"; next }
    /^#/                     { if ($0 !~ /^#### (Common|Advanced) Options/) section = ""; next }

    section == "" { next }
    $0 !~ /^\|/   { next }
    $0 ~ /^\|[ \-|]+\|$/ { next }   # table separator row

    {
      n = split($0, cell, "|")
      if (n < 4) next
      path = unwrap(cell[2])
      if (path == "" || path == "Parameter") next

      # Descriptions may contain pipes; rejoin everything after the default cell.
      desc = cell[4]
      for (i = 5; i < n; i++) desc = desc "|" cell[i]

      printf "%s{\"path\":\"%s\",\"default\":\"%s\",\"description\":\"%s\",\"section\":\"%s\"}",
        (count++ ? "," : ""), esc(path), esc(trim(cell[3])), esc(trim(desc)), section
    }

    BEGIN { printf "[" }
    END   { printf "]\n" }
  ' "$1"
}

all="$work/all.json"
echo '{}' > "$all"

shopt -s nullglob
captures=("$charts_dir"/*.txt)
[ ${#captures[@]} -gt 0 ] || { echo "no captures found in $charts_dir" >&2; exit 1; }

for capture in "${captures[@]}"; do
  name="$(basename "$capture" .txt)"
  distribution="${name%%-*}"
  version_type="${name#*-}"

  if [ "$distribution" = "$name" ]; then
    echo "skipping $name: expected a <distribution>-<versionType>.txt name" >&2
    continue
  fi

  rm -f "$work"/doc[123]
  split_docs "$capture"

  for doc in doc1 doc2 doc3; do
    [ -f "$work/$doc" ] || { echo "$name: missing document $doc" >&2; exit 1; }
  done

  chart_json="$(yq -o=json -I=0 \
    '{"name": .name, "version": .version, "appVersion": .appVersion, "description": .description}' \
    "$work/doc1")"
  values_json="$(yq -o=json '.' "$work/doc2")"
  options_json="$(parse_options "$work/doc3")"

  jq \
    --arg distribution "$distribution" \
    --arg versionType "$version_type" \
    --argjson chart "$chart_json" \
    --argjson values "$values_json" \
    --argjson options "$options_json" \
    '.[$distribution][$versionType] = {chart: $chart, values: $values, options: $options}' \
    "$all" > "$all.next"
  mv "$all.next" "$all"

  echo "$name: $(jq '.options | length' <<<"{\"options\": $options_json}") documented options" >&2
done

{
  echo "// Generated by scripts/gen-chart-data.sh from charts/*.txt — do not edit by hand."
  echo "// Keys mirror js/data.js: CHART_DATA[distribution][versionType]."
  printf 'const CHART_DATA = %s;\n' "$(jq -S . "$all")"
} > "$out_file"

echo "wrote $out_file" >&2
